2023-01-08 23:41:31,165 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Configure stats pid to 38988
2023-01-08 23:41:31,165 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Loading settings from C:\Users\opben\.config\wandb\settings
2023-01-08 23:41:31,165 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Loading settings from c:\Users\opben\OneDrive\Documents\Esh Release Radar\wandb\settings
2023-01-08 23:41:31,165 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-08 23:41:31,165 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-01-08 23:41:31,166 INFO    MainThread:38988 [wandb_init.py:_log_setup():476] Logging user logs to c:\Users\opben\OneDrive\Documents\Esh Release Radar\wandb\run-20230108_234131-edabfxma\logs\debug.log
2023-01-08 23:41:31,166 INFO    MainThread:38988 [wandb_init.py:_log_setup():477] Logging internal logs to c:\Users\opben\OneDrive\Documents\Esh Release Radar\wandb\run-20230108_234131-edabfxma\logs\debug-internal.log
2023-01-08 23:41:31,166 INFO    MainThread:38988 [wandb_init.py:init():516] calling init triggers
2023-01-08 23:41:31,166 INFO    MainThread:38988 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2023-01-08 23:41:31,166 INFO    MainThread:38988 [wandb_init.py:init():569] starting backend
2023-01-08 23:41:31,167 INFO    MainThread:38988 [wandb_init.py:init():573] setting up manager
2023-01-08 23:41:31,186 ERROR   MainThread:38988 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\wandb_init.py", line 1078, in init
    run = wi.init()
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\wandb_init.py", line 574, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\wandb_manager.py", line 173, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\service\service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\lib\sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
