2023-01-08 23:40:45,173 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Configure stats pid to 38988
2023-01-08 23:40:45,174 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Loading settings from C:\Users\opben\.config\wandb\settings
2023-01-08 23:40:45,174 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Loading settings from c:\Users\opben\OneDrive\Documents\Esh Release Radar\wandb\settings
2023-01-08 23:40:45,174 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-08 23:40:45,174 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-01-08 23:40:45,174 INFO    MainThread:38988 [wandb_init.py:_log_setup():476] Logging user logs to c:\Users\opben\OneDrive\Documents\Esh Release Radar\wandb\run-20230108_234045-2fiukwum\logs\debug.log
2023-01-08 23:40:45,175 INFO    MainThread:38988 [wandb_init.py:_log_setup():477] Logging internal logs to c:\Users\opben\OneDrive\Documents\Esh Release Radar\wandb\run-20230108_234045-2fiukwum\logs\debug-internal.log
2023-01-08 23:40:45,175 INFO    MainThread:38988 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001D54CCE8730>
2023-01-08 23:40:45,175 INFO    MainThread:38988 [wandb_init.py:init():516] calling init triggers
2023-01-08 23:40:45,175 INFO    MainThread:38988 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2023-01-08 23:40:45,175 INFO    MainThread:38988 [wandb_init.py:init():569] starting backend
2023-01-08 23:40:45,176 INFO    MainThread:38988 [wandb_init.py:init():573] setting up manager
2023-01-08 23:40:45,178 INFO    MainThread:38988 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2023-01-08 23:40:45,180 INFO    MainThread:38988 [wandb_init.py:init():580] backend started and connected
2023-01-08 23:40:45,183 INFO    MainThread:38988 [wandb_run.py:_label_probe_notebook():1116] probe notebook
2023-01-08 23:40:45,183 INFO    MainThread:38988 [wandb_run.py:_label_probe_notebook():1126] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-01-08 23:40:45,183 INFO    MainThread:38988 [wandb_init.py:init():658] updated telemetry
2023-01-08 23:40:45,262 INFO    MainThread:38988 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2023-01-08 23:41:26,028 WARNING MsgRouterThr:38988 [router.py:message_loop():77] message_loop has been closed
2023-01-08 23:41:26,028 WARNING MsgRouterThr:38988 [router.py:message_loop():77] message_loop has been closed
2023-01-08 23:41:26,028 WARNING MsgRouterThr:38988 [router.py:message_loop():77] message_loop has been closed
2023-01-08 23:41:30,675 WARNING MainThread:38988 [wandb_init.py:init():1099] interrupted
Traceback (most recent call last):
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\wandb_init.py", line 1078, in init
    run = wi.init()
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\wandb_init.py", line 697, in init
    result = handle.wait(
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\lib\mailbox.py", line 261, in wait
    found = self._slot._get_and_clear(timeout=wait_timeout)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\lib\mailbox.py", line 118, in _get_and_clear
    if self._wait(timeout=timeout):
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\lib\mailbox.py", line 114, in _wait
    return self._event.wait(timeout=timeout)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-01-08 23:41:31,165 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Configure stats pid to 38988
2023-01-08 23:41:31,165 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Loading settings from C:\Users\opben\.config\wandb\settings
2023-01-08 23:41:31,165 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Loading settings from c:\Users\opben\OneDrive\Documents\Esh Release Radar\wandb\settings
2023-01-08 23:41:31,165 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-08 23:41:31,165 INFO    MainThread:38988 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-01-08 23:41:31,166 INFO    MainThread:38988 [wandb_init.py:_log_setup():476] Logging user logs to c:\Users\opben\OneDrive\Documents\Esh Release Radar\wandb\run-20230108_234131-edabfxma\logs\debug.log
2023-01-08 23:41:31,166 INFO    MainThread:38988 [wandb_init.py:_log_setup():477] Logging internal logs to c:\Users\opben\OneDrive\Documents\Esh Release Radar\wandb\run-20230108_234131-edabfxma\logs\debug-internal.log
2023-01-08 23:41:31,166 INFO    MainThread:38988 [wandb_init.py:init():516] calling init triggers
2023-01-08 23:41:31,166 INFO    MainThread:38988 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2023-01-08 23:41:31,166 INFO    MainThread:38988 [wandb_init.py:init():569] starting backend
2023-01-08 23:41:31,167 INFO    MainThread:38988 [wandb_init.py:init():573] setting up manager
2023-01-08 23:41:31,186 ERROR   MainThread:38988 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\wandb_init.py", line 1078, in init
    run = wi.init()
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\wandb_init.py", line 574, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\wandb_manager.py", line 173, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\service\service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\lib\sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\opben\.conda\envs\esh-release-radar\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
